### ISSUE TITLE
open programaticaly

### ISSUE THREAD

**Issue by LeonAlvarez** [syropian/vue-tribute#10]
Can this be open with tribute.showMenuForCollection() ? I cant find way to do so

**Comment by LeonAlvarez** [comment]
this.$refs.tribute.YourTributeRef.showMenuForCollection(this.$refs.YourInputRef);

**Comment by iedmrc** [comment]
I also need this, could you please explain more?

**Comment by StCyr** [comment]
Yeah, not that easy.

I'm trying `this.$refs.tribute.tribute.showMenuForCollection(this.$refs.composerInput)` from an input button.

This adds a trigger character at the end of my composerInput element but nothing else.

I think that my button should somehow contain the text to look for in tribute but I'm really not sure...

PS: I've tried to pass the text via `this.$refs.tribute.tribute.current.mentionText = '@mention'`, but that's not it.

PS2: I think I'll just duplicate the code of my tribute 'values' and 'selectTemplate' functions to directly add the text in my composeInput without using tribute.
