### ISSUE TITLE
Options only takes an object

### ISSUE THREAD

**Issue by sarah-due** [syropian/vue-tribute#13]
Tribute allows for an array of collection objects, but in this wrapper you can only pass a single collection object.

**Comment by syropian** [comment]
@sarah-due If you look at the core Tributejs docs you'l see you still have to pass an object as the core config, but you put your array of config objects inside a `collection` key. This is the same way you'd achieve collections with this wrapper.

Here's an example you can check out: https://codesandbox.io/s/x7z8op666o

Let me know if that works for you!

**Comment by sarah-due** [comment]
Ahhh brilliant, thank you!!

**Comment by syropian** [comment]
You're very welcome! 🙌
