### ISSUE TITLE
How to implement a NoMatchTemplate?

### ISSUE THREAD

**Issue by apbln** [syropian/vue-tribute#14]
In the docs of tribute it says:

![grafik](https://user-images.githubusercontent.com/38110721/54079352-2ce53280-42db-11e9-9169-94e34314be31.png)

But if I add this line to my collection nothing happens, when I type a word that isn't in my feed after my trigger
![grafik](https://user-images.githubusercontent.com/38110721/54079256-bc89e180-42d9-11e9-84f1-12e637ee3391.png)

I read there should be a tribute instance given as a paremter inside a function here, which returns a string as mine, but how could I do this in vue

Could someone show an working example on codesandbix.io as here 
https://codesandbox.io/s/vq1nm7oyq3

**Comment by syropian** [comment]
The `noMatchTemplate` has to be _outside_ your collections as outlined in this issue: https://github.com/zurb/tribute/issues/155#issuecomment-433397272

Looks like they might be adding collection support for it in the future, but for now, that's the only way to include it.

I've updated the CodeSandbox example to include an example of it working.

**Comment by apbln** [comment]
thanks a lot
