### ISSUE TITLE
Can't continue via spacebar if NoMatchTemplate() AND spaceSelectsMatch are active

### ISSUE THREAD

**Issue by apbln** [syropian/vue-tribute#15]
![grafik](https://user-images.githubusercontent.com/38110721/54093848-53b76d80-439c-11e9-805b-77d9664cf96c.png)
![grafik](https://user-images.githubusercontent.com/38110721/54093958-64b4ae80-439d-11e9-99ec-cb0089134353.png)
Obviously _spaceSelectsMatch_ awaits a match to continue and it doesn't consider a new tag being written. I have to unfocus the editor and focus again to continue.

**Comment by syropian** [comment]
That _sounds_ like a bug with the core library, not this wrapper. I'd probably confirm and then file an issue in the [tribute repo](https://github.com/zurb/tribute)
