### ISSUE TITLE
How to force Menu to update?

### ISSUE THREAD

**Issue by apbln** [syropian/vue-tribute#18]
While typing I'm pushing new values into the collection dynamically. Of course, the NoMatchTemplate pops up, because the values were not there in the beginning. But how could I force the menu to recheck if there are actually items in the values, so the selectTemplate shows up again?

I've asked this yesterday in the core tribute, but couldn't find a solution. Maybe you can help.

https://github.com/zurb/tribute/issues/233

Would it help to push values via the remoteSearch-function? And if so, do you have an example?
The goal is to push maximum five matching values (if there are any) into the component's values for performance reasons.

**Comment by BghinC** [comment]
Hey,

Probably too late but it could be useful for those having the same issue.
With the recent update (https://github.com/syropian/vue-tribute/commit/0f98b64386452b6ecd87898143197f38dd72ac43) the collection is dynamically updated when new values are pushed.

However the drop-down list disappears until a key is pushed. You can simulate a keydown event followed by a keyup event to make it appears again with the new changes.

For now it is the only one solution I've found and I didn't detect any side effect while the user is typing.

Best
