### ISSUE TITLE
How to load remote data (remoteSearch-function)?

### ISSUE THREAD

**Issue by apbln** [syropian/vue-tribute#19]
How do I use this in vue : https://github.com/zurb/tribute#loading-remote-data
for example with this Fake Online REST API: https://jsonplaceholder.typicode.com/

**Comment by Flourad** [comment]
how to use the remote search?

**Comment by syropian** [comment]
@Flourad There's nothing special you need to do to use remote search with this component, just follow the instructions on the Tribute repo — https://github.com/zurb/tribute#loading-remote-data
