### ISSUE TITLE
I this repo still maintained? 

### ISSUE THREAD

**Issue by hd-diegocortez** [syropian/vue-tribute#22]
Seems like it does not.

**Comment by syropian** [comment]
what makes you think it isn’t?

**Comment by hd-diegocortez** [comment]
@syropian  Well, I see no responses in opened issues, that's why I asked. Is that not enough?

**Comment by syropian** [comment]
Because the open issues are very difficult to understand, and have little to no context. Almost every issue someone opens is usually a question better asked in the Tribute repo. This package is a very simple wrapper.

**Comment by hd-diegocortez** [comment]
> what makes you think it isn’t?

Cool, I was just answering your question. It would be nice that you -as a member- respond with something on those issues though.

**Comment by syropian** [comment]
I’m not really obligated to do so, since I don’t get paid to maintain this package. Any time someone has posted a clear and concise issue, I’ve responded accordingly. 

I’m a busy person, and sometimes I forget to respond to issues that are low-effort or don’t make sense. It doesn’t mean the repo isn’t maintained.

**Comment by hd-diegocortez** [comment]
That's why I said "would be nice" not "you must". I understand if you're a busy person, I understand also if you're not a nice person as well. Good luck with whatever. :)

**Comment by syropian** [comment]
Seems like a really hostile thing to say to someone just because you made a bad assumption about the state of this repo. 

If you don’t like how this repo is run, please feel free to open source your own wrapper 😄
