### ISSUE TITLE
menuContainer doesn't works

### ISSUE THREAD

**Issue by FabricioSouza88** [syropian/vue-tribute#25]
Have you ever heard of a situation where menuContainer doesn't work?
I am trying to use it as follows:
menuContainer: document.getElementById ('section-master')

The result of getElementById returns the element correctly, but the panel always opens in the body.

**Comment by syropian** [comment]
Can you check out https://github.com/syropian/vue-tribute/issues/7 for the correct way to do it?

**Comment by syropian** [comment]
@FabricioCollins Did the linked solution work ok for you?

**Comment by FabricioSouza88** [comment]
@syropian , I'm getting back to working on it now,
I used 
`tributeDefaults.menuContainer = document.getElementById("section-grid") `
and got the error 
"vue.esm.js?efeb:3270 Uncaught RangeError: Maximum call stack size exceeded".

I looked ate the console, and my call to ID "section-grid" return just one element, is just a DIV inside my body. I'm still investigating, but if somebody knows this error, please share us. I tell if get a solution.
Thasks

**Comment by FabricioSouza88** [comment]
@syropian , apparently it doesn't work when using 'collections', as I could reproduce in the link https://codesandbox.io/s/vue-tribute-menu-container-example-q7x6d

**Comment by syropian** [comment]
@FabricioCollins Thanks, I’ll try and look into this soon. I have a busy few days ahead, and probably won’t get to it until early next week. 

<sub>Sent with <a href="http://githawk.com">GitHawk</a></sub>

**Comment by FabricioSouza88** [comment]
@syropian , I think I found the problem. When using 'collection', the menuContainer parameter is not inside the collection item, but remains within .options, and I didn't know it.

Thanks for the help always agile and congratulate on the beautiful component.
Thanks from Brazil!!
