### ISSUE TITLE
needs to be updated for Vue 2

### ISSUE THREAD

**Issue by seandearnaley** [syropian/vue-tribute#3]
Vue directives have changed.. tried tweaking the project myself but there are some fundamental differences which are a challenge to overcome.

**Comment by syropian** [comment]
Hm yeah, it may make sense to convert it to an actual component, as directives have much less access to things now.

**Comment by tobischw** [comment]
An update for Vue2 would be fantastic. I may try to port it myself.

**Comment by syropian** [comment]
Just a heads up I've almost finished up Vue 2 support, I just need to update the docs and examples. Sit tight!

**Comment by MohamedHana** [comment]
Can you please show an example of using it with Vue 2?
With features & events?

**Comment by goldsteinr** [comment]
Nice :)

**Comment by syropian** [comment]
Update is out, please see the readme for example usage.

**Comment by tobischw** [comment]
Thank you.
