### ISSUE TITLE
Highlight the menions

### ISSUE THREAD

**Issue by reverie-ss** [syropian/vue-tribute#4]
How to highlight the mentions?

**Comment by syropian** [comment]
This library does not provide any styling by default. You can include the [basic stylesheet](https://github.com/zurb/tribute/blob/master/dist/tribute.css) provided by the original plugin to get you started.

**Comment by Issabln** [comment]
@reverie-ss did you find a way?

**Comment by reverie-ss** [comment]
> @reverie-ss did you find a way?

not exactly a solution, but i remember i had figured out a workaround!
![untitled](https://user-images.githubusercontent.com/14177137/53620454-09eeba80-3c19-11e9-9aa6-fff4f556c45e.png)

**Comment by syropian** [comment]
@Issabln @reverie-ss Apologies for prematurely closing this, I think I misunderstood your question. 

Fortunately, the solution is fairly simple! First of all, you need to be using an element with `contenteditable="true"`, not an input or textarea. After that you just need to pass a `selectTemplate` function in your tribute options.

```
selectTemplate(item) {
  return '<mark>@' + item.original.value + '</mark>';
}
```

Result:

![](https://d.pr/i/Giqq9M+)

**Comment by apbln** [comment]
@syropian  could you show an example of a component using this feature?

**Comment by syropian** [comment]
@apbln https://codesandbox.io/s/vq1nm7oyq3

See the `App.vue` file

Type a `@` or `#` in the textbox.
