### ISSUE TITLE
The Tribute.js version packaged in the build is too outdated

### ISSUE THREAD

**Issue by djramones** [syropian/vue-tribute#41]
I'm one of those who prefer to use JS libraries from the public CDNs, but unfortunately the current builds for this project incorporate the 3.5.3 version of `tributejs`. That's old enough to miss out on features like `autocompleteMode`.

I'm still not too familiar with the Node packaging system but I managed to do a basic `npm up tributejs` which bumped up the version to 3.7.3. Not a great improvement knowing that Tribute is in 5.x now, but it was enough to get me `autocompleteMode`.

Would be nice if we could get an even more recent version, with a build pushed onto the CDNs. I'm just not privy to the intricacies of dependencies, so I can't do it myself yet without probably breaking some things.

(Thank you by the way, dear author/maintainer, for this nice little wrapper!)

**Comment by amdp** [comment]
#metoo !

**Comment by vbasky** [comment]
Is there any update on this ?

**Comment by syropian** [comment]
Hi all, I just published a minor update that accepts any tributejs version >= 2.0.0 as its peer dependency, as they all should work with this wrapper.

**Comment by syropian** [comment]
Fixed in 4a788110b35d4e241ee91145341cdc1cde4b8f91
