### ISSUE TITLE
How to handle? Active State Detection

### ISSUE THREAD

**Issue by hijax231** [syropian/vue-tribute#45]
im just wondering how to implement zurb Active State Detection thanks using vue tribute

**Comment by syropian** [comment]
I'm not sure what you mean by "active state detection", could you provide a link? Thanks!

**Comment by eliottvincent** [comment]
Hey! What we do at Crisp is to watch the `isActive` property of the Tribute instance:

```
watch: {
  "tribute.isActive": {
    handler(isActive) {
      // Store the status or do whatever you want
      this.tributeActive = isActive;
    }
  }
}
```

**Comment by syropian** [comment]
Considering this closed as there hasn't been a further response.
