### ISSUE TITLE
Autocomplete removes the next character

### ISSUE THREAD

**Issue by potatozerg** [syropian/vue-tribute#48]
I'm not sure if it's better to submit an issue for the original package. Please let me know if I should do that (they are quite inactive).

The question I have is if I have:
`SUM(x)`

when I try to replace x with something by autocomplete, it will replace the next character with space, in this case, ')'.
`SUM(x)` ---> `SUM( real_column `

Is there any way to fix this except adding space in the formula? 
`SUM( x )` ---> `SUM( real_column)` this still doesn't look good.

**Comment by syropian** [comment]
This would definitely be an issue for the Tribute.js library, this wrapper doesn't modify any behaviour related to how autocomplete works. Sorry!
