### ISSUE TITLE
Does this work in Vue3?

### ISSUE THREAD

**Issue by joekaiser** [syropian/vue-tribute#57]
I'm getting an error `TypeError: h is not a function`. I'm not sure if it is me or the project. Does this work in Vue3?

**Comment by syropian** [comment]
Hi @joekaiser, I haven't thought to check yet, since this is the first issue I'm seeing about it. Let me take a peek this weekend, and I'll push a fix once I confirm.

**Comment by syropian** [comment]
I confirmed it does not currently work with Vue 3. I will hopefully push an update for this on Sunday.

**Comment by syropian** [comment]
Hello!

I've just tagged a `v2.0.0` release that is compatible with Vue 3. It can be installed by using the `next` dist-tag.

```bash
$ npm install vue-tribute@next --save
# or...
$ yarn add vue-tribute@next
```

Installation and usage instructions can be found on the [next branch](https://github.com/syropian/vue-tribute/tree/next).
