### ISSUE TITLE
menuContainer option doesn't work

### ISSUE THREAD

**Issue by Truemedia** [syropian/vue-tribute#7]
So when trying to set a custom container for easier positioning of the mentions box relative to the input the container is always null when part of any of my vue components.

I know this is probably down to when the instance is initialised that vue might be still processing but I'm kind of stuck as to how I can either delay the instance being created or update the instance options on the fly when vue is done rendering.

I guess something like this is happening for the input, so would it be the case this can be done for the menuContainer option aswell?

**Comment by packytagliaferro** [comment]
@Truemedia did you get this to work? I also get `undefined`

I tried `menuContainer: document.getElementById("reply-comment"),` to attach to my textarea.

Also tried `menuContainer: self.$refs.reply` with `ref='reply'` on my textarea

**Comment by Truemedia** [comment]
@packytagliaferro  Yeh so my strategy was watching the message change then doing some dom transforms to get my desired result. Hacky but workable

**Comment by i-ira** [comment]
> @packytagliaferro Yeh so my strategy was watching the message change then doing some dom transforms to get my desired result. Hacky but workable

can you please elaborate on your method more? maybe show some code?

**Comment by mart1nra** [comment]
@Truemedia hi, could you please share your code to see how you did dom transforms? Thanks!

**Comment by syropian** [comment]
Hi all, I just published a new version – `1.0.3`, that should fix this issue. A few notes:

1. You **must** define `menuContainer` in your initial options. You can safely set it to `document.body` as a default.
2. Set the new menu container value somewhere like `mounted()`. You should be able to safely use refs here.
3. You also need to set `positionMenu` to `false` in your Tribute options. This is required when using the `menuContainer` option.
4. Ensure your menu container element has `position: relative` or (less likely) `position: absolute` or your menu will still position itself incorrectly.

I've created a quick Codesandbox to demonstrate it working: https://codesandbox.io/s/vue-tribute-menu-container-example-lfyxn

**Comment by FabricioSouza88** [comment]
@syropian, I've created a Codesandbox based on your exemple. I'm not sure, but apparently, menuContainer doesn't work when using definition based on 'collection'. Using standard definition it works fine.
My exemple here: 
https://codesandbox.io/s/vue-tribute-menu-container-example-q7x6d
