### ISSUE TITLE
showMenuForCollection

### ISSUE THREAD

**Issue by lijingying91** [syropian/vue-tribute#74]
How can I use “showMenuForCollection” this fucntion in vue-tribute？

**Comment by syropian** [comment]
Hey @lijingying91 !

You can access the underlying `Tribute` instance directly on the input it's bound to. Simply add a `ref` to the input and then access the `Tribute` instance with `tributeInstance`. Something like this _should_ work:

```vue
<script setup>
const tributeInput = ref(null);

function showMenu() {
  if (!tributeInput.value?.tributeInstance) return;
  
  tributeInput.value.tributeInstance.showMenuForCollection(tributeInput.value)
}
</script>

<template>
  <vue-tribute :options="options">
    <input type="text" placeholder="@..." ref="tributeInput" />
  </vue-tribute>
  
  <button type="button" @click="showMenu">Show menu</button>
</template>
```

Let me know if that helps!

**Comment by lijingying91** [comment]
> Hey @lijingying91 !
> 
> You can access the underlying `Tribute` instance directly on the input it's bound to. Simply add a `ref` to the input and then access the `Tribute` instance with `tributeInstance`. Something like this _should_ work:
> 
> ```
> <script setup>
> const tributeInput = ref(null);
> 
> function showMenu() {
>   if (!tributeInput.value?.tributeInstance) return;
>   
>   tributeInput.value.tributeInstance.showMenuForCollection(tributeInput.value)
> }
> </script>
> 
> <template>
>   <vue-tribute :options="options">
>     <input type="text" placeholder="@..." ref="tributeInput" />
>   </vue-tribute>
>   
>   <button type="button" @click="showMenu">Show menu</button>
> </template>
> ```
> 
> Let me know if that helps!

it works. thank you
