### ISSUE TITLE
How to use v-model?

### ISSUE THREAD

**Issue by standnguyen197** [syropian/vue-tribute#8]
How to use v-model?

**Comment by syropian** [comment]
@standnguyen197 How would you envision `v-model` working for this component?

**Comment by wadewilliams** [comment]
Was struggling with this today - 

```
<template>
  <vue-tribute :options="options" ref="tribute">
    <textarea v-model="body" @tribute-replaced="updateFromTribute"></textarea>
  </vue-tribute>
</template>
<script>
...
data (){
  body:  ''
},
...
methods: {
  updateFromTribute (e) {
    this.body = e.target.value
  }
}
</script>
```

☝️ Seems to work fine. @syropian let me know if there is a better way or if this is best practice. Happy to send a PR to update docs/example as this seems like a normal use.
